import unittest
import os, sys
from gmpy2 import mpz
import gmpy2

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from Crypto.SecurityParams              import SecurityParams, secparams_default, secparams_l0, secparams_l3
from TestParams                         import testparams
from Types                              import *
from Utils.ToString                     import ToString
from Utils.MarkByteArray                import MarkByteArray
from Utils.XorByteArray                 import XorByteArray
from PrintingAuthority.GetSheet         import GetSheet

def GetSheets(v, c, n, k, E, D, secparams = secparams_default):
    """
    Algorithm 7.13: Computes the list s = (S_1, ..., S_N) of code sheets for every voter. A
    single code sheet is represented as a String S_i \in A_UCS^* which is generated by Alg. 7.14

    Args:
        V (list):   Voter description
        c (list):   List of candidate descriptions
        n (int):    Number of candidates
        k (int):    Number of selections
        E (list):   Eligibility Matrix
        D (tuple):  Code Sheet Data

    Returns:
        list:       code sheet
    """

    s = []
    for i in range (len(D)): # Check! len(D) must be = s (num of authorities)
        k_i = [E[i][j] * k[j] for j in range(len(k))]
        X = ToString(sum(D[0]), secparams.l_X, secparams.A_X)   # Voting Code
        Y = ToString(sum(D[1]), secparams.l_Y, secparams.A_Y)   # Confirmation Code
        F_i = D[i]
        FC = ToString(XorByteArray([F_i[j] for j in range(F_i)]), secparams.A_F)

        rc = []
        R_i = D[3][i]
        for k in range(len(c)):
            R = MarkByteArray(XorByteArray([R_i[j][k] for j in range(len(R_i))]), k, max(n))
            rc.append(ToString(R, secparams.A_R))
            s.append(GetSheet(i, v[i], c, n, k_i, X, Y, FC, rc))

    return s
