---
version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 0.0.0.0:27017:27017/tcp
  backend:
    build: ./backend
    ports:
      - 0.0.0.0:5000:5000/tcp
    environment:
      - MONGODB_HOST=mongodb
      - SOCKETIO_HOST=0.0.0.0
      - SOCKETIO_PORT=5000
    depends_on:
      - mongodb
    links:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 0.0.0.0:8080:8080/tcp
    volumes:
      - ./frontend/node_modules:/var/www/node_modules
    depends_on:
      - backend
    links:
      - backend
