# vim: expandtab tabstop=2 :
---
version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017/tcp
  backend:
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - 5000:5000/tcp
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8080:8080/tcp
