# vim: expandtab tabstop=2 :
---
version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 0.0.0.0:27018:27018/tcp
  backend:
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - 0.0.0.0:5000:5000/tcp
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 0.0.0.0:8080:8080/tcp
    environment:
      SOCKETIO_BASE_URL: https://chvote.virvum.ch/ws
