# vim: expandtab tabstop=2 :
---
version: '3'
services:
  mongodb:
    ports:
      - 0.0.0.0:27017:27017/tcp
  backend:
    ports:
      - 0.0.0.0:5000:5000/tcp
    environment:
      SOCKETIO_HOST: 0.0.0.0
      SOCKETIO_PORT: 5000
  frontend:
    ports:
      - 0.0.0.0:8080:8080/tcp
    environment:
      SOCKETIO_BASE_URL: /socket.io
