import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import gmpy2
from gmpy2 import mpz
import unittest
from SecurityParams import secparams_default, secparams_l0, secparams_l3
from Utils import Truncate, AssertMpz, ToInteger
from RecHash import RecHash

def GetPublicVoterData(D_hat, electionEvent, secparams = secparams_default):
    """
    Algorithm 7.12: Computes lists x^ and y^ of public voter credentials, which are obtained by 
    multiplying corresponding values from the public parts of electorate data generated by the authorities.
   
    @type   D_hat:  tuple
    @param  D_hat:  Contains s public voter parameter entries (d_hat_j)

    @rtype:     Tuple
    @return:    Public data
    """ 

    x_hat = []
    y_hat = []
    for i in range (0, electionEvent.N):  # loop over N (voters)
        x_hat_i = mpz(1)
        y_hat_i = mpz(1)
        for j in range(0, secparams_default.s): # loop over s (authorities)
            x_hat_i *= D_hat[i][j][0]   # multiply all x values
            y_hat_i *= D_hat[i][j][1]   # multiply all y values

        x_hat.append(x_hat_i)
        y_hat.append(y_hat_i)
    return (x_hat, y_hat)
